#!/bin/bash

# Initialize git helper shell
/usr/share/git/completion/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE="1"
GIT_PS1_SHOWUNTRACKEDFILES="1"
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCONFLICTSTATE="yes"
GIT_PS1_DESCRIBE_STYLE="describe"
GIT_PS1_SHOWCOLORHINTS="1"

PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
