#!/bin/bash

# FZF
export FZF_DEFAULT_OPTS='
	--preview=" \
		[[ $(file --mime {}) =~ binary ]] &&
			echo {} is a binary file ||
			(less {} | bat --color always --tabs 8 --theme \"Monokai Extended\" --wrap auto {}) 2> /dev/null
	"
	--preview-window="right:hidden"
	--height="100%"
	--bind="ctrl-h:preview-down,ctrl-l:preview-up,ctrl-p:toggle-preview,ctrl-y:execute-silent(echo -n {} | xclip -selection c)+abort"
'

# Set default editor
export EDITOR=nvim

# Set default browser
export BROWSER=/usr/bin/google-chrome-stable

# Set default terminal
export TERMINAL=/usr/bin/terminator
