#!/bin/bash

# Set default editor
export EDITOR=nvim
# Set default editor for systemd
export SYSTEMD_EDITOR="$EDITOR"

# Set default browser
export BROWSER=/usr/bin/google-chrome-stable

# Set default terminal
export TERMINAL=/usr/bin/terminator
