#!/bin/bash

# Source nvm
source /usr/share/nvm/init-nvm.sh

# Smart completion for npm commands
if command -v npm &> /dev/null; then
	source <(npm completion)
fi

# Smart completion for composer
# see https://github.com/bamarni/symfony-console-autocomplete
if command -v symfony-autocomplete &> /dev/null; then
	source <(symfony-autocomplete)
fi

# Smart completion for pip
if command -v pip &> /dev/null; then
	source <(pip completion --bash)
fi

# Smart completion for pipx
if command -v pipx &> /dev/null && command -v register-python-argcomplete &> /dev/null; then
	eval "$(register-python-argcomplete pipx)"
fi

# Smart completion for arch-audit
if command -v arch-audit &> /dev/null; then
	source <(arch-audit completions bash)
fi

# Smart completion for op (1password cli client)
if command -v op &> /dev/null; then
	source <(op completion bash)
fi

# Smart completion for op (auto-cpufreq cli client)
if command -v auto-cpufreq &> /dev/null; then
	eval "$(_AUTO_CPUFREQ_COMPLETE=bash_source auto-cpufreq)"
fi
