#!/bin/bash

# Source nvm
source /usr/share/nvm/init-nvm.sh

# Smart completion for npm commands
#
# Just an empty placeholder so NPM does not crash if missing...
# The actual auth token (if available) should go to ~/.localrc

if command -v npm &> /dev/null; then
	source <(NPM_TOKEN="${NPM_TOKEN:-}" npm completion)
fi

# Smart completion for composer
# see https://github.com/bamarni/symfony-console-autocomplete
if command -v symfony-autocomplete &> /dev/null; then
	source <(symfony-autocomplete)
fi

# Smart completion for pip
if command -v pip &> /dev/null; then
	source <(pip completion --bash)
fi

if command -v arch-audit &> /dev/null; then
	source <(arch-audit completions bash)
fi
