#!/bin/bash

DOTFILES=(
	".bash_aliases"			\
	".bash_logout"			\
	".bash_profile"			\
	".bash_prompt"			\
	".bashrc"			\
	".ctags"			\
	".editorconfig"			\
	".editrc"			\
	".exports"			\
	".fzf.bash"			\
	".gitconfig"			\
	".gitignore_global"		\
	".inputrc"			\
	".misc"				\
	".my.cnf"			\
	".myclirc"			\
	".notags"			\
	".path"				\
	".selected_editor"		\
	".tmux.conf"			\
	".vimrc"			\
)

SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P )"

print_help() {
	printf "%s" "\
Usage: $0
		[-h | --help]
		<command>

Options:
	-h | --help
		Show this help

Commands:
	import
		Import dotfiles from the current user's home directory.
		See \`$0 list\` for all files.
	export
		Export all dotfiles from this repository into the current user's
		home directory.
	list
		List all available dotfiles in the current user's home
		directory. These files are going to be imported by
		\`$0 import\`
	help
		Show this help
"
}

import_dotfiles() {
	echo "Imported the following files:"
	for dotfile in "${DOTFILES[@]}"; do
		if [ ! -d "${SCRIPTPATH}/dotfiles/${dotfile}" ]; then
			mkdir -p "${SCRIPTPATH}/dotfiles/$(dirname $dotfile)"
		fi
		if [ -f "${HOME}/${dotfile}" ]; then
			cp "${HOME}/${dotfile}" "${SCRIPTPATH}/dotfiles/${dotfile}"
			echo "${HOME}/${dotfile}"
		fi
	done;
}

export_dotfiles() {
	echo "Export the following files:"
	for dotfile in "${DOTFILES[@]}"; do
		if [ ! -d "${HOME}/$(dirname $dotfile)" ]; then
			mkdir -p "${HOME}/$(dirname $dotfile)"
		fi
		cp "${SCRIPTPATH}/dotfiles/${dotfile}" "${HOME}/${dotfile}"
		echo "$dotfile"
	done;
}

list_dotfiles() {
	echo "Dotfiles to be considered are:"
	for dotfile in "${DOTFILES[@]}"; do
		if [ -f "${HOME}/${dotfile}" ]; then
			echo "${HOME}/${dotfile}";
		fi
	done;
}

case "$1" in
	-h | --help | help)
		print_help
		;;
	import)
		import_dotfiles
		;;
	export)
		export_dotfiles
		;;
	list)
		list_dotfiles
		;;
	*)
		echo "Command not found" >&2
		echo "Hint: $0 --help"
		exit 1
esac
